name: project-lifecycle
on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled
permissions: {}

jobs:
  lifecycle:
    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@ec5a7f83fb1f5b03707118050147a70fd115c231
    with:
      # These files to sync are OSS things which have no place here
      filesToIgnore: "CODE_OF_CONDUCT.md,LICENSE,SECURITY.md,CODEOWNERS,GOVERNANCE.md,CONTRIBUTING.md"
    secrets:
      app_id: ${{ secrets.KONG_MESH_APP_ID }}
      private_key: ${{ secrets.KONG_MESH_APP_PRIVATE_KEY }}
